const:
  projName: ecommerce
  port: 8080
  
server:
  port: ${const.port}
  context-path: /${const.projName}

spring:
  datasource:
    url: jdbc:mysql://rm-wz9253yt7qwahue48o.mysql.rds.aliyuncs.com:3306/ecommerce?characterEncoding=utf8&useSSL=true&serverTimezone=UTC
    username: yeehom
    password: Qq123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  http:
    encoding.charset: UTF-8
    encoding.enable: true
    encoding.force: true

mybatis:
    typeAliasesPackage: com.yeehom.ecommerseminiprog.pojo
    mapperLocations: classpath:mybatis/mapper/*.xml
    configLocation: classpath:mybatis/mybatis-config.xml